---
- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml

- name: Configure networking for swarm ingress
  ansible.builtin.include_tasks: configure_host_network.yml

# Create a docker swarm of all hosts in the docker group
- name: Configure docker swarm
  ansible.builtin.include_tasks: configure_swarm.yml

- name: Configure overlay network(s)
  ansible.builtin.include_tasks: configure_overlay_network.yml
  loop: "{{ overlay_networks }}"
  when: overlay_networks is defined and overlay_networks is iterable
